### ISSUE TITLE
Error on startup.

### ISSUE THREAD

**Issue by boby360** [georgeherby/MADevice#10]
Starting Device Checker Script
Starting check on 192.168.0.46:5000
General error Expecting value: line 1 column 1 (char 0)
Issues in the checker tread exception was: 'NoneType' object is not iterable
Logged in. Username: xxxx. User ID:xxxx
Status request received for Server

on !status call in discord general error is given again. any suggestions?

**Comment by boby360** [comment]
virt enviroment wasn't created however mad doesn't run in that enviroment.

**Comment by georgeherby** [comment]
I'd guess you are missing something in your config. Can you post config.ini and servers.json

**Comment by boby360** [comment]
It's all pretty simple stuff.
discord_token=xxxxx
duration_before_alert=15
delay_between_checks=5

[
  {
    "ip": "192.168.0.46:5000",
    "name": "Server",
    "webhook": "https://discordapp.com/api/webhooks/xxxxxx",
    "status_channel_id": xxxxx,
    "username": "xxxx",
    "password": "xxxxx",
    "alert_role_id": xxxx
  }
  ]

No json errors.

**Comment by georgeherby** [comment]
OK, so that looks fine. Please, can you run MADevice in debug `-v` and put the whoel log in pastebin and post the link here?

**Comment by boby360** [comment]
[     ScanChecker] [     connector:23] [   ERROR] General error Expecting value: line 1 column 1 (char 0)
[     ScanChecker] [         alert:96] [   ERROR] Issues in the checker tread exception was: 'NoneType' object is not iterable

shows up. it does the starting check. that appears. and then it shows logged in.

**Comment by georgeherby** [comment]
Please make sure you are using the develop branch

**Comment by boby360** [comment]
Iv followed instruction to use venv. No change. Rechecked all files for text formatting and file format. I didn't think dev had any significant changes that would resolve the issue but I will pull it and test.

**Comment by boby360** [comment]
My own stupidity. This was a simple wrong login. Let it be known as of this version this is the error that will be shown for a wrong login.
