### ISSUE TITLE
Madevice crash when MAD is off/not respond

### ISSUE THREAD

**Issue by cyphercris** [georgeherby/MADevice#20]
When MAD is off or crash, madevice is crashed and needed to restart. It will be great to avoid it and send notification when its not possible to connect server

**Comment by darkelement1987** [comment]
Can confirm the issue.

**Comment by Axiangel** [comment]
Handling this and instead letting it trigger another alarm would be Awesome! ^^

**Comment by georgeherby** [comment]
I have fixed this on the develop branch

**Comment by georgeherby** [comment]
This is now merged to master
