### ISSUE TITLE
Discord BOT goes offline

### ISSUE THREAD

**Issue by kamieniarz** [georgeherby/MADevice#21]
I'm running MADevice on 3 different VPS. Each one uses the same Discord Bot and same webhook but from time to time Discord Bot simply goes offline so `!status` doesn't work at all. Webhook obviously works so I'm still getting new updates if something doesn't work properly. Also there is no error in logs. The only way to fix this issue is to restart MADevice on each VPS

I'm not the only one having that issue

**Comment by mimikq** [comment]
i have the same issue bot is offline but if device failed i got notification

**Comment by BoB3R** [comment]
Same here =/

**Comment by kamieniarz** [comment]
Issue can be related with sending differend command than `!status`. I just sent sommand to bot from PoracleJS (`!unregister @user`) and MADevice bot went offline immidiately. I revokeed read channel permissions for my bot. It's possible that that was an issue

**Comment by kamieniarz** [comment]
I just made few tests and I guess there is an issue when bot from MADevice has access to the same channel as bot from PoracleJS. I have no idea why and how it's possible but I suggest you to separate these 2 bots ;)

**Comment by georgeherby** [comment]
I will be honest I am not sure what you are reporting as the issue here?

**Comment by BoB3R** [comment]
Hello,
It looks like MADevice is having problems with other bot commands that are issued from the same VPS (as I understand it). Basically when someone issue command to Poracle, MADevice go offline and you can't issue "!status". It still reporting if there is no data for X mintes. When any command from Poracle like "!poracle" is issued bot for MADevice go offline. I restricted my MADevice do read only one channel and it's working fine now. Not sure where the issues is.

**Comment by georgeherby** [comment]
Are you on the most recent develop build?

**Comment by BoB3R** [comment]
Hello, I was before. I see that there is a new build.

**Comment by kamieniarz** [comment]
I'm on develop. Issue is gone after I separated MADevice bot from PoracleJS bot

**Comment by mimikq** [comment]
i'm not sure, time when i read this post there was a develop branch but not i cant see it and our bot is still down, strange is that when ATV stucks or etc we received warrning but cmd !status is not working coz but is offline.  any ideas how can i run it in some debug mode or how can i provide logs ? 

Thanks

**Comment by georgeherby** [comment]
So, i have been informed in #31 that a bump in the discord bot client will stop this issue!
