### ISSUE TITLE
Currently not compatible with mad

### ISSUE THREAD

**Issue by gcm-explo1t** [georgeherby/MADevice#26]
With the current status of MAD and MADevice i only get: Server <myserver> is not available to get status

could you please fix this :)

**Comment by georgeherby** [comment]
Erm well care to share some information, are they both on the most recent versions of master? A log maybe

**Comment by gcm-explo1t** [comment]
MADevice Log:
`Jan 27 13:45:11 tobiasmadl.de python3[2398]:  [01-27 13:45:11] [     ScanChecker] [         alert:33] [    INFO] Starting Device Checker Script
Jan 27 13:45:11 tobiasmadl.de python3[2398]:  [01-27 13:45:11] [     ScanChecker] [         alert:41] [    INFO] Starting check on 127.0.0.1:5000
Jan 27 13:45:11 tobiasmadl.de python3[2398]:  [01-27 13:45:11] [     ScanChecker] [     connector:32] [    INFO] Sending alert to Discord as server is not available
Jan 27 13:45:11 tobiasmadl.de python3[2398]:  [01-27 13:45:11] [     ScanChecker] [     connector:47] [   ERROR] No connection adapters were found for '127.0.0.1:5000/get_status'
Jan 27 13:45:11 tobiasmadl.de python3[2398]:  [01-27 13:45:11] [     ScanChecker] [         alert:97] [    INFO] All device checks completed, going to sleep
`
MAD on git commit: 838f593 (Sun Jan 26 14:26:56 2020)
MADevice on git commit: a1106bf (Thu Jan 16 20:55:51 2020)

3 weeks ago everything worked fine

**Comment by gcm-explo1t** [comment]
> Erm well care to share some information, are they both on the most recent versions of master? A log maybe

Above is the Log, do you have any idea, what could be the problem @georgeherby

**Comment by gcm-explo1t** [comment]
Fixed it by adding "http://" in servers.json.
